apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flask-cpu-autoscale
  namespace: devops-project
spec:
  scaleTargetRef:
    name: flask-app
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 5
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"